#### general settings
name: EDSR

use_tb_logger: true
model: EDSR
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train: # 'train' is used as dataset['phase'] at option.py
    name: train
    mode: EDSR
    dataroot_GT: ../../REDS/train_sharp #D:/REDS/train_sharp # ../datasets/DF2K/generated/tdsr/HR  # D:/REDS/sintel_GT
    dataroot_LQ: ../../REDS/train_sharp_bicubic/X4 #D:/REDS/train_sharp_bicubic/X4 # ../datasets/DF2K/generated/tdsr/LR  # D:/REDS/sintel_LR
    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 16
    GT_size: 192
    use_flip: true
    use_rot: true
    color: RGB
    data_type: img
    #    scale: ~  # written at option.py
  val: # 'val' is used as dataset['phase'] at option.py
    name: val
    mode: EDSR
    dataroot_GT: ../../REDS/val_sharp # D:/REDS/val_sharp #../../../ntire20/DIV2K_valid_HR
    dataroot_LQ: ../../REDS/val_sharp_bicubic/X4 # D:/REDS/val_sharp_bicubic/X4 # ../../../ntire20/Corrupted-va-x
    data_type: img
    #    phase: ~  # written at option.py
    #    scale: ~  # written at option.py

#### network structures
network_EDSR:
  which_model: EDSR
  n_resgroups: 10
  n_resblocks: 16
  n_feats: 64
  scale: 4
  rgb_range: 1  # 255
  n_colors: 3
  res_scale: 1
  shift_mean: True
  precision: single
  gan_k: 1  # k value for adversarial loss

#### path
path:
  pretrain_model: H:/Proposed/experiments/EDSR/models/60000_G.pth
  strict_load: true
  resume_state: H:/Proposed/experiments/EDSR/training_state/60000.state
  root: H:/Proposed              # written at option.py
  #  experiment_root:  ~  # written at option.py
  #  test_root:  ~        # written at option.py
  #  models: ~            # written at option.py
  #  training_state: ~    # written at option.py
  #  val_images:  ~       # written at option.py

#### training settings: learning rate scheme, loss
train:
  lr: !!float 1e-4
  lr_decay: 200
  weight_decay: 0
  beta1: 0.9
  beta2: 0.999
  epsilon: !!float 1e-8

  total_epochs: 300
  gamma: 0.5  # 'learning rate decay factor for step decay'

  pixel_criterion: l1
  pixel_weight: 1

  skip_threshold: !!float 1e6 # skipping batch that has large error

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 1
  val_freq: !!float 1e4

#### logger
## tensorboard --logdir ./tb_logger --port=6006
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
