#### general settings
name: RCAN

use_tb_logger: true
model: RCAN
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: train
    mode: RCAN  # DRB / DRB_no_patch / LQGT / RCAN
    dataroot_GT: D:/REDS/train_sharp # ../datasets/DF2K/generated/tdsr/HR  # D:/REDS/sintel_GT
    dataroot_LQ: D:/REDS/train_sharp_bicubic/X4 # ../datasets/DF2K/generated/tdsr/LR  # D:/REDS/sintel_LR
    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 16
    GT_size: 192
    use_flip: true
    use_rot: true
    color: RGB
    data_type: img
  val:
    name: val
    mode: RCAN
    dataroot_GT: D:/REDS/val_sharp # D:/REDS/val_sharp #../../../ntire20/DIV2K_valid_HR
    dataroot_LQ: D:/REDS/val_sharp_bicubic/X4 # D:/REDS/val_sharp_bicubic/X4 # ../../../ntire20/Corrupted-va-x
    data_type: img

#### network structures
network_RCAN:
  which_model: RCAN
  n_resgroups: 10
  n_resblocks: 20
  n_feats: 64
  reduction: 16
  scale: 4
  rgb_range: 1  # 255
  n_colors: 3
  res_scale: 1
  shift_mean: True
  precision: single
  gan_k: 1  # k value for adversarial loss



#### path
path:
  pretrain_model: ../experiments/RCAN/models/120000_G.pth
  strict_load: true
  resume_state: ../experiments/RCAN/training_state/120000.state

#### training settings: learning rate scheme, loss
train:
  lr: !!float 1e-4
  lr_decay: 200
  weight_decay: 0
  beta1: 0.9
  beta2: 0.999
  epsilon: !!float 1e-8

  total_epochs: !!float 1e8
  gamma: 0.5  # 'learning rate decay factor for step decay'

  pixel_criterion: l1
  pixel_weight: 1

  skip_threshold: !!float 1e6 # skipping batch that has large error

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 1
  val_freq: !!float 1e4

#### logger
## tensorboard --logdir ./tb_logger --port=6006
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e4
