#### general settings
name: DBPN

use_tb_logger: true
model: DBPN
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train: # 'train' is used as dataset['phase'] at option.py
    name: train
    mode: DBPN
    dataroot_GT: ../../REDS/train_sharp #D:/REDS/train_sharp # ../datasets/DF2K/generated/tdsr/HR  # D:/REDS/sintel_GT
    dataroot_LQ: ../../REDS/train_sharp_bicubic/X4 #D:/REDS/train_sharp_bicubic/X4 # ../datasets/DF2K/generated/tdsr/LR  # D:/REDS/sintel_LR
    use_shuffle: true
    n_workers: 0  # per GPU
    batch_size: 10
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
    data_type: img
    #    scale: ~  # written at option.py
  val: # 'val' is used as dataset['phase'] at option.py
    name: val
    mode: DBPN
    dataroot_GT: ../../REDS/val_sharp # D:/REDS/val_sharp #../../../ntire20/DIV2K_valid_HR
    dataroot_LQ: ../../REDS/val_sharp_bicubic/X4 # D:/REDS/val_sharp_bicubic/X4 # ../../../ntire20/Corrupted-va-x
    data_type: img
    #    phase: ~  # written at option.py
    #    scale: ~  # written at option.py

#### network structures
network_DBPN:
  which_model: DBPN
  num_channels: 3
  base_filter: 64
  n_feats: 256
  num_stages: 3
  scale: 4
  rgb_range: 255  # 255



#### path
path:
  pretrain_model: H:/Proposed/experiments/DBPN/models/10000_G.pth
  strict_load: true
  resume_state: H:/Proposed/experiments/DBPN/training_state/10000.state
  root: H:/Proposed              # written at option.py
  #  experiment_root:  ~  # written at option.py
  #  test_root:  ~        # written at option.py
  #  models: ~            # written at option.py
  #  training_state: ~    # written at option.py
  #  val_images:  ~       # written at option.py

#### training settings: learning rate scheme, loss
train:
  lr: !!float 1e-4
  lr_decay: !!float 5e5
  weight_decay: !!float 1e-4
  beta1: 0.9
  beta2: 0.999
  epsilon: !!float 1e-8

  niter: !!float 1e6
  gamma: 0.1  # 'learning rate decay factor for step decay'

  pixel_criterion: l1
  pixel_weight: 1

  manual_seed: 123
  val_freq: !!float 1e4

#### logger
## tensorboard --logdir ./tb_logger --port=6006
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
