#### general settings
name: DRB9_2_net_GT_720_batch_1_block_n_4_lrDRB_1e-4_pixelShuffle_pix_cb_1e-3_fea_l1_1e-2_TP300000_x5_min_1e-7
# pix fea
# l1  l1   1e-1 1e-6
# l1  l2   1e-1 1e-6
# l1  cb   1e-1 1e-12
# l2  l1   1e-1 1e-7
# l2  l2   1e-1 1e-7
# l2  cb   1e-1 1e-13
# cb  l1   1e-3 1e-2
# cb  l2   1e-3 1e-2
# cb  cb   1e-3 1e-8
use_tb_logger: true
model: DRB
distortion: sr
scale: 4
gpu_ids: [1]

#### datasets
datasets:
  train:
    name: train
    mode: DRB # DRB / DRB_no_patch
    aug: ~ #noise
    noise_data: ../datasets/DF2K/Corrupted_noise/
    dataroot_GT: ../../REDS/train_sharp/ # ../datasets/DF2K/generated/tdsr/HR
    dataroot_LR: ../../REDS/train_sharp_bicubic/X4/ # ../datasets/DF2K/generated/tdsr/LR
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 1
    GT_size: 720
    use_flip: true
    use_rot: true
    color: RGB
    data_type: seq
    position: mid # side_1st // side 2nd // mid
    ref_frame_num: 5 # 3 / 5 / 7 ...
  val:
    name: val
    mode: DRB
    dataroot_GT: ../../REDS/val_sharp/ #../../../ntire20/DIV2K_valid_HR
    dataroot_LR: ../../REDS/val_sharp_bicubic/X4/ # ../../../ntire20/Corrupted-va-x
    data_type: seq
    position: mid # side_1st // side 2nd // mid
    ref_frame_num: 5 # 3 / 5 / 7 ...

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23

network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64

network_DRB:
  which_model_DRB: DRB9_2_block4
  rgb_range: 1

#### path
path:
  pretrain_model_G: ../pretrained_model/RRDB_PSNR_x4.pth
  pretrain_model_DRB: #../experiments/DRB9_2_net_GT_720_batch_1_block_n_6_lrDRB_1e-4_pixelShuffle_pix_cb_1e-3_fea_l1_1e-2_TP300000_x5_min_1e-7/models/750000_G.pth
  strict_load: true
  resume_state: #../experiments/DRB9_2_net_GT_720_batch_1_block_n_6_lrDRB_1e-4_pixelShuffle_pix_cb_1e-3_fea_l1_1e-2_TP300000_x5_min_1e-7/training_state/750000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999

  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999

  lr_DRB: !!float 1e-4
  weight_decay_DRB: 0
  beta1_DRB: 0.9
  beta2_DRB: 0.999

  niter: 1200001
  warmup_iter: -1  # no warm up

  # MultiStepLR_Restart
#  lr_scheme: MultiStepLR_Restart
#  lr_steps: [30000, 60000, 90000, 120000, 150000, 180000, 210000, 240000, 270000, 300000, 330000, 360000]
#  restarts: ~
#  restart_weights: ~

  # CosineAnnealingLR_Restart
#  lr_scheme: CosineAnnealingLR_Restart
#  # four
#  T_period: [30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000, 30000]
#  restarts: [30000, 60000, 90000, 120000, 150000, 180000, 210000, 240000, 270000, 300000, 330000, 360000, 390000, 420000, 450000]
#  restart_weights: [ 0.99, 0.891, 0.8019, 0.7217, 0.6495, 0.5846, 0.5261, 0.4735, 0.4262, 0.3835, 0.3452, 0.3107, 0.2796, 0.2516, 0.2265]
#  eta_min: !!float 1e-7

  #  # CosineAnnealingLR_Restart
  lr_scheme: CosineAnnealingLR_Restart
  # four
  T_period: [300000, 300000, 300000, 300000, 300000]
  restarts: [300000, 600000, 900000, 1200000]
  restart_weights: [1, 0.75, 0.675, 0.6075]
  eta_min: !!float 1e-7

  lr_gamma: 0.5

  pixel_criterion: cb   # l1 / cb
  pixel_weight: !!float 1e-3 # !!float 1e-2
  feature_criterion: l1 # l1 / cb
  feature_weight: !!float 1e-2
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

# pix fea
# l1  l1   1e-1 1e-6
# l1  l2   1e-1 1e-6
# l1  cb   1e-1 1e-12
# l2  l1   1e-1 1e-7
# l2  l2   1e-1 1e-7
# l2  cb   1e-1 1e-13
# cb  l1   1e-3 1e-2
# cb  l2   1e-3 1e-2
# cb  cb   1e-3 1e-8

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 6e4

#### logger
## tensorboard --logdir ./tb_logger --port=6006
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e4


# server ssh
  # ssh icsp@166.104.36.34

# watch nvidia
  # watch -n 0.5 -d nvimia-smi

# server tensor board
# PC: ssh -L 16006:localhost:6006 icsp@166.104.36.34
# server:
#  conda activate Dissertation
#  tensorboard --logdir nvme1/Dissertation/tb_logger
#  cd nvme1/Dissertation/codes


