#### general settings
name: DRB_SR
use_tb_logger: true
model: DRB
distortion: sr
scale: 4
gpu_ids: [4]

#### datasets
datasets:
  train:
    name: train
    mode: DRB
    aug: ~ #noise
    noise_data: ../datasets/DF2K/Corrupted_noise/
    dataroot_GT: C:/Users/wee/Pytorch_Projects/Proposed/dataset/train/GT # D:/REDS/train_sharp # ../datasets/DF2K/generated/tdsr/HR
    dataroot_LR: C:/Users/wee/Pytorch_Projects/Proposed/dataset/X4 #D:/REDS/train_sharp_bicubic/X4 # ../datasets/DF2K/generated/tdsr/LR
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    GT_size: 128
    use_flip: true
    use_rot: true
    color: RGB
    data_type: seq
    position: mid # side_1st // side 2nd // mid
    ref_frame_num: 5 # 3 / 5 / 7 ...
  val:
    name: val
    mode: DRB
    dataroot_GT: C:/Users/wee/Pytorch_Projects/Proposed/dataset/val/GT # D:/REDS/val_sharp #../../../ntire20/DIV2K_valid_HR
    dataroot_LR: C:/Users/wee/Pytorch_Projects/Proposed/dataset/val/X4 # D:/REDS/val_sharp_bicubic/X4 # ../../../ntire20/Corrupted-va-x
    data_type: seq
    position: mid # side_1st // side 2nd // mid
    ref_frame_num: 5 # 3 / 5 / 7 ...

#### network structures
network_G:
  which_model_G: RRDBNet
  in_nc: 3
  out_nc: 3
  nf: 64
  nb: 23
network_D:
  which_model_D: discriminator_vgg_128
  in_nc: 3
  nf: 64
network_DRB:
  which_model_DRB: DRB_mid # DRB_1st // DRB_2nd

#### path
path:
  pretrain_model_G: ../pretrained_model/RRDB_PSNR_x4.pth
  pretrain_model_DRB: ~
  pretrain_model_Flow: ../pretrained_model/gma-sintel.pth
  strict_load: true
  resume_state: ../experiments/DRB_SR/training_state/60000.state

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.999
  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.999

  lr_DRB: !!float 1e-4
  weight_decay_DRB: 0
  beta1_DRB: 0.9
  beta2_DRB: 0.999

  lr_scheme: MultiStepLR

  niter: 600001
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2  # 1
  feature_criterion: l1
  feature_weight: 1
  gan_type: ragan  # gan | ragan
  gan_weight: !!float 5e-3

  D_update_ratio: 1
  D_init_iters: 0

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
## tensorboard --logdir ./tb_logger --port=6006
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
